steps:
  # pull the last container image
- name: "gcr.io/cloud-builders/docker"
  args: ["pull", "europe-docker.pkg.dev/kovzy-322715/prod/auth-backend:latest"]
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args:
  - build
  - -t
  - europe-docker.pkg.dev/kovzy-322715/prod/auth-backend:latest
  - --cache-from
  - europe-docker.pkg.dev/kovzy-322715/prod/auth-backend:latest
  - .
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "europe-docker.pkg.dev/kovzy-322715/prod/auth-backend:latest"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=k8s.yaml
  - --location=europe-west3
  - --cluster=kovzy-prod
