apiVersion: v1
kind: Service
metadata:
  name: auth-backend
  namespace: msvc
spec:
  ports:
    - port: 9000
      name: auth-backend
  clusterIP: None
  selector:
    app: auth-backend
    namespace: msvc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-backend
  namespace: msvc
spec:
  selector:
    matchLabels:
      app: auth-backend  # has to match .spec.template.metadata.labels
      namespace: msvc
  serviceName: auth-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-backend  # has to match .spec.selector.matchLabels
        namespace: msvc
    spec:
      containers:
        - name: auth-backend
          image: europe-docker.pkg.dev/kovzy-322715/prod/auth-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
              name: auth-backend
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 10m
              memory: 50Mi